services:
  premio-java11:
    build:
      context: ..
      dockerfile: java11-sshd/Dockerfile
    image: java11-sshd:latest
    container_name: premio-java11
#    restart: unless-stopped
    environment:
      SSH_USER: dev
      DOCKER_HOST: unix:///var/run/dind/docker.sock
    ports:
      - "2222:22"
    volumes:
      - type: bind
        source: ${WORKSPACE_SOURCE:-.}
        target: /workspace/premio-java
        bind:
          create_host_path: true
      - premio-maven:/home/dev/.m2
      - premio-gradle:/home/dev/.gradle
      - dind-runtime:/var/run/dind
      - type: bind
        source: ${WORKSPACE_RESOURCE:-.}/openvpn
        target: /etc/openvpn/client
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${WORKSPACE_RESOURCE:-.}/ssh/keys
        target: /home/dev/.ssh/shared/keys
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${WORKSPACE_RESOURCE:-.}/ssh/config
        target: /home/dev/.ssh/shared/config
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${WORKSPACE_RESOURCE:-.}/ssh/authorized_keys
        target: /home/dev/.ssh/shared/authorized_keys
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${WORKSPACE_RESOURCE:-.}/aws
        target: /home/dev/.aws
        bind:
          create_host_path: false
    networks:
      - dev-dind

volumes:
  premio-maven:
  premio-gradle:
  dind-runtime:
    external: true

networks:
  dev-dind:
    external: true
